chore: remove react integration
spotify/confidence-sdk-js pull request #120
Opened 2024-04-30 08:34 UTC by nicklasl

Requires https://github.com/spotify/confidence-openfeature-provider-js/pull/119

2024-04-30 10:12 UTC, andreas-karlsson reviewed
Looks good to me, although ideally we'd want the latest version in npm to mention that it's deprecated somehow... or it doesn't really matter pre 1.0 and we just merge this?

2024-04-30 11:36 UTC, andreas-karlsson requested changes
We should first release a version where the readme explains it's deprecated and to use OpenFeature react sdk instead.

2024-04-30 11:56 UTC, nicklasl commented
Here's the PR that adds the deprecation notice: https://github.com/spotify/confidence-openfeature-provider-js/pull/123

2024-05-03 12:51 UTC, andreas-karlsson approved these changes

2024-05-06 08:29 UTC, fabriziodemaria approved these changes

2024-05-06 08:29 UTC, merged